# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_shoal_wrappers", use_symbols = TRUE, package_name = "shoal")

#' @usage NULL
#' @useDynLib shoal, .registration = TRUE
NULL

rust_dbscan <- function(x, eps, min_samples, metric) .Call(wrap__rust_dbscan, x, eps, min_samples, metric)

rust_hdbscan <- function(x, alpha, min_samples, min_cluster_size, metric, boruvka, partial_labels) .Call(wrap__rust_hdbscan, x, alpha, min_samples, min_cluster_size, metric, boruvka, partial_labels)

rust_dist <- function(x, metric, p) .Call(wrap__rust_dist, x, metric, p)

rust_hclust <- function(d, n, method) .Call(wrap__rust_hclust, d, n, method)

rust_kmeans <- function(x, k, init, n_runs, max_iter, tolerance, seed) .Call(wrap__rust_kmeans, x, k, init, n_runs, max_iter, tolerance, seed)

rust_nearest_centroid <- function(x, centroids) .Call(wrap__rust_nearest_centroid, x, centroids)

rust_gmm <- function(x, k, init, n_runs, max_iter, tolerance, reg_covariance, seed) .Call(wrap__rust_gmm, x, k, init, n_runs, max_iter, tolerance, reg_covariance, seed)


# nolint end
